confutils/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, re_path, include
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    re_path("", include("pc_nomination.urls")),
    re_path(r"^admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r"^static/(?P<path>.*)$", serve),
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {"document_root": settings.MEDIA_ROOT, "show_indexes": True},
        ),
    ]


# ==================
#    ERROR RENDER
# ==================


def error_render(request, template, status):
    response = render(request, template, locals())
    response.status_code = status
    return response


def error_400_view(request, exception):
    return error_render(request, "400.html", 400)


def error_403_view(request, exception):
    return error_render(request, "403.html", 403)


def error_404_view(request, exception):
    return error_render(request, "404.html", 404)


def error_500_view(request):
    return error_render(request, "500.html", 500)


handler400 = error_400_view
handler403 = error_403_view
handler404 = error_404_view
handler500 = error_500_view

pc_nomination/urls.py
from django.urls import re_path

from . import views

app_name = "programcommittee"
urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^logout$", views.logout, name="logout"),
    re_path(r"^manage/?$", views.manage, name="manage"),
    re_path(r"^manage/duplicates/?$", views.duplicate_index, name="duplicate_index"),
    re_path(
        r"^manage/duplicates/(?P<duplicate_id>[0-9+]+)/?$",
        views.duplicate,
        name="duplicate",
    ),
    re_path(r"^manage/export/csv/?$", views.export_csv, name="export_csv"),
    re_path(r"^manage/export/ec/?$", views.export_ec, name="export_ec"),
    re_path(r"^api/check_entry/?$", views.check_entry, name="check_entry"),
]

pc_nomination/models.py
from django.db import models

from pc_nomination.choices import AREA_CHOICES, PHD_DATE_CHOICES


class Area(models.Model):
    slug_name = models.SlugField(max_length=50, choices=AREA_CHOICES, unique=True)
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Nomination(models.Model):
    first_name = models.CharField(max_length=50, verbose_name="first name")
    last_name = models.CharField(max_length=50, verbose_name="last name")
    full_name = models.CharField(max_length=100, verbose_name="full name")
    dblp = models.URLField(verbose_name="DBLP url")
    added_date = models.DateTimeField()
    proposer = models.CharField(
        max_length=50, verbose_name="Proposer identifier", blank=True, null=True
    )
    areas = models.ManyToManyField(
        Area,
        related_name="persons",
        blank=True,
    )
    phd_date = models.CharField(
        verbose_name="PhD delivery date",
        max_length=50,
        choices=PHD_DATE_CHOICES,
        blank=True,
        null=True,
    )
    comment = models.TextField()
    ec_invited = models.BooleanField(
        verbose_name="Invited on EasyChair", blank=True, null=True, default=False
    )
    ec_accepted = models.BooleanField(
        verbose_name="Invitation accepted on EasyChair",
        blank=True,
        null=True,
        default=False,
    )
    in_reserve = models.BooleanField(
        verbose_name="In the reserve list", blank=True, null=True, default=False
    )

    class Meta:
        ordering = ["full_name"]

    def __str__(self):
        return self.full_name + " - " + self.dblp


class EmailAddress(models.Model):
    email = models.EmailField()
    person = models.ForeignKey(
        Nomination, related_name="emails", on_delete=models.CASCADE
    )

    class Meta:
        ordering = ["email"]

    def __str__(self):
        return f"{self.person.full_name} - {self.email}"


class Duplicate(models.Model):
    nomination1 = models.ForeignKey(
        Nomination, on_delete=models.CASCADE, related_name="conflicts_as_1"
    )
    nomination2 = models.ForeignKey(
        Nomination, on_delete=models.CASCADE, related_name="conflicts_as_2"
    )
    reason = models.TextField()
    ignored = models.BooleanField(default=False)

    class Meta:
        ordering = ["nomination1", "nomination2"]

    def __str__(self):
        return f"{self.nomination1.full_name} - {self.nomination2.full_name}"

pc_nomination/views.py
import csv
import os.path
import tempfile
from io import StringIO

from datetime import datetime
from urllib.parse import urlparse

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.core.management import call_command
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse
from django.utils.dateparse import parse_date
from django.db.models import Q
from django.http import JsonResponse
from django.contrib.auth import logout as django_logout

from .forms import (
    NominationForm,
    ProposerForm,
    ImportFileForm,
    UpdateNominationForm,
    DuplicateResolverForm,
)
from .models import Nomination, EmailAddress, Area, Duplicate


def logout(request):
    django_logout(request)
    return redirect("programcommittee:index")


# ==================
#    AJAX QUERIES
# ==================


def check_entry(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name", "")
        first_name = " ".join(first_name.split())
        last_name = request.POST.get("last_name", "")
        last_name = " ".join(last_name.split())
        email = request.POST.get("email", "")
        dblp = request.POST.get("dblp", "")
        # print(f"Received query: {email}, {dblp} for {first_name} {last_name}")

        if len(first_name) + len(last_name) + len(email) + len(dblp) > 2:
            similar_persons = None
            if email:
                similar_emails_pks = EmailAddress.objects.filter(
                    email__iexact=email
                ).values_list("pk", flat=True)
                similar_persons = Nomination.objects.filter(
                    emails__in=similar_emails_pks
                )
                # print(f"Emails: {similar_persons}")
            if not similar_persons:
                if dblp:
                    similar_persons = Nomination.objects.filter(dblp__iexact=dblp)
                    # print(f"DBLP: {similar_persons}")
                if not similar_persons and len(last_name) + len(first_name) > 2:
                    first_name_query = None
                    last_name_query = None
                    if first_name:
                        first_name_query = (
                            Q(first_name__icontains=first_name)
                            | Q(first_name__istartswith=first_name)
                            | Q(last_name__icontains=first_name)
                            | Q(last_name__istartswith=first_name)
                        )
                    if last_name:
                        last_name_query = (
                            Q(first_name__icontains=last_name)
                            | Q(first_name__istartswith=last_name)
                            | Q(last_name__icontains=last_name)
                            | Q(last_name__istartswith=last_name)
                        )
                    if first_name_query or last_name_query:
                        if first_name_query and last_name_query:
                            name_query = first_name_query & last_name_query
                        elif first_name_query:
                            name_query = first_name_query
                        else:
                            name_query = last_name_query
                        similar_persons = Nomination.objects.filter(name_query)
                        # print(f"Name: {similar_persons}")
            if similar_persons:
                return_val = set()
                for p in similar_persons:
                    url_parse = urlparse(p.dblp)
                    if url_parse.hostname == "dblp.org":
                        return_val.add(
                            f'{p.full_name} - <a href="{p.dblp}">{p.dblp}</a>'
                        )
                    else:
                        return_val.add(f"{p.first_name} {p.last_name}")
                return JsonResponse({"similar_persons": list(return_val)})
        return JsonResponse({"notfound": "No one found", "similar_persons": []})
    return JsonResponse({"error": "Invalid request"})


def index(request):
    if request.GET.get("logout", None):
        request.session.flush()
        return redirect("programcommittee:index")

    context = {}

    add_person_form = NominationForm()
    proposer_id_form = None
    if request.method == "POST":
        if "proposer_id_form" in request.POST:
            proposer_id_form = ProposerForm(request.POST)
            if proposer_id_form.is_valid():
                request.session["_proposer_id"] = proposer_id_form.cleaned_data[
                    "identifier"
                ]
        elif "add_person_form" in request.POST:
            add_person_form = NominationForm(request.POST)
            if add_person_form.is_valid():
                full_name = add_person_form.cleaned_data["full_name"]
                first_name = add_person_form.cleaned_data["first_name"]
                last_name = add_person_form.cleaned_data["last_name"]
                split_full_name = [s.lower() for s in full_name.split(" ")]
                if (
                    last_name.lower() not in split_full_name
                    or first_name.lower() not in split_full_name
                ):
                    full_name_split = full_name.split(" ")
                    first_name = full_name_split[0]
                    last_name = " ".join(full_name_split[1:])
                nomination = Nomination.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    full_name=full_name,
                    dblp=add_person_form.cleaned_data["dblp"],
                    proposer=request.session.get("_proposer_id"),
                    comment=add_person_form.cleaned_data["comment"],
                    phd_date=add_person_form.cleaned_data["phd_date"],
                    added_date=datetime.now(),
                )
                try:
                    email = EmailAddress.objects.create(
                        person=nomination,
                        email=add_person_form.cleaned_data["email"].lower(),
                    )
                    try:
                        for area in add_person_form.cleaned_data["areas"]:
                            nomination.areas.add(Area.objects.get(slug_name=area))
                        nomination.save()
                        context["added_nomination"] = nomination
                    except Exception as e:
                        email.delete()
                        raise e
                except Exception as e:
                    nomination.delete()
                    raise e
                add_person_form = NominationForm()
        else:
            raise Http404("POST request but unknown form type.")

    proposer_id = request.session.get("_proposer_id", None)
    context["proposer_id"] = proposer_id

    if proposer_id:
        proposed = Nomination.objects.filter(proposer=proposer_id)
        context["proposed"] = proposed
    else:
        proposer_id_form = ProposerForm()

    context["proposer_id_form"] = proposer_id_form
    context["add_person_form"] = add_person_form
    return render(request, "programcommittee/index.html", context)


@login_required
@staff_member_required
def manage(request):
    context = {}
    if request.method == "POST" and "csv_form" in request.POST:
        csv_form = ImportFileForm(request.POST, request.FILES)
        if csv_form.is_valid():
            uploaded_file = request.FILES["csv_file"]
            file_name = FileSystemStorage(location=tempfile.gettempdir()).save(
                uploaded_file.name, uploaded_file
            )
            params = {"accepted": False, "invited": False, "reserve": False}
            action = csv_form.cleaned_data["action"]
            if action in ["invited", "accepted"]:
                params["invited"] = True
            if action == "accepted":
                params["accepted"] = True
            if action == "reserve":
                params["reserve"] = True
            try:
                out = StringIO()
                params["stdout"] = out
                call_command(
                    "import_csv",
                    os.path.join(tempfile.gettempdir(), file_name),
                    **params,
                )
                context["command_log"] = out.getvalue()
            except Exception as e:
                context["command_error"] = e.__repr__()
    else:
        csv_form = ImportFileForm()
    context["csv_form"] = csv_form

    all_nominations = Nomination.objects.all().prefetch_related("emails")
    nomination_forms = []
    for nomination in all_nominations:
        if request.method == "POST" and f"update_nom_{nomination.id}" in request.POST:
            nom_up_form = UpdateNominationForm(
                request.POST, nomination=nomination, hidden=True, prefix=nomination.id
            )
            if nom_up_form.is_valid():
                nomination.first_name = nom_up_form.cleaned_data["first_name"]
                nomination.last_name = nom_up_form.cleaned_data["last_name"]
                nomination.full_name = nom_up_form.cleaned_data["full_name"]
                nomination.dblp = nom_up_form.cleaned_data["dblp"]
                nomination.proposer = nom_up_form.cleaned_data["proposer"]
                nomination.ec_invited = nom_up_form.cleaned_data["invited"]
                nomination.ec_accepted = nom_up_form.cleaned_data["accepted"]
                nomination.in_reserve = nom_up_form.cleaned_data["reserve"]
                nomination.comment = nom_up_form.cleaned_data["comment"]
                nomination.save()
                EmailAddress.objects.filter(person=nomination).delete()
                for email in nom_up_form.cleaned_data["emails"]:

pc_nomination/templates/programcommittee/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Conf-Utils{% endblock %}</title>
    {% block extra_head %}{% endblock %}
</head>

<body>
    <header>
        {% block header %}{% endblock %}
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 Simon Rey</p>
    </footer>

    {% block extra_scripts %}{% endblock %}
</body>
</html>

pc_nomination/templates/programcommittee/duplicate_resolver.html
{% extends 'programcommittee/base.html' %}

{% block extra_head %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
{% endblock %}

{% block title %}PC Nomination | ECAI 2025{% endblock %}

{% block header %}
    <h1>ECAI-2025 &mdash; PC Member Nomination </h1>
{% endblock %}

{% block content %}
    <section>
        <div class="section-content">
            <h2>Potential Duplicate {{ duplicate.nomination1.full_name }}</h2>

            {% if resolver_form.errors %}
                <div class="form-error-message">
                    <ul>
                        {% for key, value in resolver_form.errors.items %}
                            <li>{{ key }}: {{ value }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <form class="duplicate-wrapper" method="post" action="{% url 'programcommittee:duplicate' duplicate_id=duplicate.id%}">
                {% csrf_token %}

                <div class="duplicate-table-header">First Name</div>
                <div {% if duplicate.nomination1.first_name == duplicate.nomination2.first_name %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination1.first_name }}
                </div>
                <div {% if duplicate.nomination1.first_name == duplicate.nomination2.first_name %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination2.first_name }}
                </div>
                <div>{% include 'include/contenteditable_field.html' with field=resolver_form.first_name %}</div>

                <div class="duplicate-table-header">Last Name</div>
                <div {% if duplicate.nomination1.last_name == duplicate.nomination2.last_name %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination1.last_name }}
                </div>
                <div {% if duplicate.nomination1.last_name == duplicate.nomination2.last_name %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination2.last_name }}
                </div>
                <div>{% include 'include/contenteditable_field.html' with field=resolver_form.last_name %}</div>

                <div class="duplicate-table-header">Full Name</div>
                <div {% if duplicate.nomination1.full_name == duplicate.nomination2.full_name %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination1.full_name }}
                </div>
                <div {% if duplicate.nomination1.full_name == duplicate.nomination2.full_name %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination2.full_name }}
                </div>
                <div>{% include 'include/contenteditable_field.html' with field=resolver_form.full_name %}</div>

                <div class="duplicate-table-header">DBLP</div>
                <div {% if duplicate.nomination1.dblp == duplicate.nomination2.dblp %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% if duplicate.nomination1.dblp %}
                        <a href="{{ duplicate.nomination1.dblp }}" target="_blank">{{ duplicate.nomination1.dblp }}</a>
                    {% endif %}
                </div>
                <div {% if duplicate.nomination1.dblp == duplicate.nomination2.dblp %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% if duplicate.nomination2.dblp %}
                        <a href="{{ duplicate.nomination3.dblp }}" target="_blank">{{ duplicate.nomination3.dblp }}</a>
                    {% endif %}
                </div>
                <div>{% include 'include/contenteditable_field.html' with field=resolver_form.dblp %}</div>

                <div class="duplicate-table-header">Email</div>
                <div {% if duplicate.nomination1.emails.all == duplicate.nomination2.emails.all %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% for e in duplicate.nomination1.emails.all %}
                        <p style="margin: 0">{{ e.email }}</p>
                    {% endfor %}
                </div>
                <div {% if duplicate.nomination1.emails.all == duplicate.nomination2.emails.all %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% for e in duplicate.nomination2.emails.all %}
                        <p style="margin: 0">{{ e.email }}</p>
                    {% endfor %}
                </div>
                <div>{{ resolver_form.emails }}</div>

                <div class="duplicate-table-header">Area</div>
                <div {% if duplicate.nomination1.areas.all == duplicate.nomination2.areas.all %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% for e in duplicate.nomination1.areas.all %}
                        <p style="margin: 0">{{ e }}</p>
                    {% endfor %}
                </div>
                <div {% if duplicate.nomination1.areas.all == duplicate.nomination2.areas.all %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% for e in duplicate.nomination2.areas.all %}
                        <p style="margin: 0">{{ e }}</p>
                    {% endfor %}
                </div>
                <div>{{ resolver_form.areas }}</div>

                <div class="duplicate-table-header">PhD Date</div>
                <div {% if duplicate.nomination1.phd_date == duplicate.nomination2.phd_date %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination1.phd_date }}
                </div>
                <div {% if duplicate.nomination1.phd_date == duplicate.nomination2.phd_date %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination2.phd_date }}
                </div>
                <div>{{ resolver_form.phd_date }}</div>

                <div class="duplicate-table-header">Proposer</div>
                <div {% if duplicate.nomination1.proposer == duplicate.nomination2.proposer %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination1.proposer }}
                </div>
                <div {% if duplicate.nomination1.proposer == duplicate.nomination2.proposer %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination2.proposer }}
                </div>
                <div>{% include 'include/contenteditable_field.html' with field=resolver_form.proposer %}</div>

                <div class="duplicate-table-header">Invited</div>
                <div {% if duplicate.nomination1.ec_invited == duplicate.nomination2.ec_invited %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% include "include/boolean_symbol.html" with value=duplicate.nomination1.ec_invited %}
                </div>
                <div {% if duplicate.nomination1.ec_invited == duplicate.nomination2.ec_invited %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% include "include/boolean_symbol.html" with value=duplicate.nomination2.ec_invited %}
                </div>
                <div>{{ resolver_form.ec_invited }}</div>

                <div class="duplicate-table-header">Accepted</div>
                <div {% if duplicate.nomination1.ec_accepted == duplicate.nomination2.ec_accepted %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% include "include/boolean_symbol.html" with value=duplicate.nomination1.ec_accepted %}
                </div>
                <div {% if duplicate.nomination1.ec_accepted == duplicate.nomination2.ec_accepted %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% include "include/boolean_symbol.html" with value=duplicate.nomination2.ec_accepted %}
                </div>
                <div>{{ resolver_form.ec_accepted }}</div>

                <div class="duplicate-table-header">Reserve</div>
                <div {% if duplicate.nomination1.in_reserve == duplicate.nomination2.in_reserve %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% include "include/boolean_symbol.html" with value=duplicate.nomination1.in_reserve %}
                </div>
                <div {% if duplicate.nomination1.in_reserve == duplicate.nomination2.in_reserve %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {% include "include/boolean_symbol.html" with value=duplicate.nomination2.in_reserve %}
                </div>
                <div>{{ resolver_form.in_reserve }}</div>

                <div class="duplicate-table-header">Comment</div>
                <div {% if duplicate.nomination1.comment == duplicate.nomination2.comment %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination1.comment }}
                </div>
                <div {% if duplicate.nomination1.comment == duplicate.nomination2.comment %}class="duplicate-table-no-diff-row"{% else %}class="duplicate-table-diff-row"{% endif %}>
                    {{ duplicate.nomination2.comment }}
                </div>
                <div>{{ resolver_form.comment }}</div>

                <div></div>
                <div></div>
                <div><input class="button" style="background: var(--color-warning-dark);" type="submit" value="Tag Duplicate as Ignored" name="ignore_duplicates"></div>
                <div><input class="button" style="background: var(--color-success-dark);"type="submit" value="Resolve Duplicate" name="resolve_duplicates"></div>
            </form>
        </div>
    </section>
{% endblock %}

{% block extra_scripts %}
    <script>
        function resizeTextArea(textarea) {
            $(textarea).height(0);
            $(textarea).height(textarea.scrollHeight + "px");
        }

        $(document).ready(function () {
            $('div[contenteditable]').on('input', function () {
                const targetId = $(this).data('for');
                $('#' + targetId).val($(this).text());
                updateFullName();
            });

            $('textarea').on('input', function () {
                resizeTextArea(this);
            });
            $('textarea').each(function() {
                resizeTextArea(this);
            });

            const first_name_input = $('#id_first_name');
            const last_name_input = $('#id_last_name');
            const full_name_input = $('#id_full_name');
            const full_name_edit_div = $('#id_full_name_div');

            function updateFullName() {
                var fullName = first_name_input.val() + ' ' + last_name_input.val();
                full_name_input.val(fullName);
                full_name_edit_div.html(fullName);
            }
        });
    </script>
{% endblock %}

pc_nomination/templates/programcommittee/duplicates_none.html
{% extends 'programcommittee/base.html' %}

{% block extra_head %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
{% endblock %}

{% block title %}PC Nomination | ECAI 2025{% endblock %}

{% block header %}
    <h1>ECAI-2025 &mdash; PC Member Nomination </h1>
{% endblock %}

{% block content %}
    <section>
        <div class="section-content">
            <p>There are no duplicates, <a href="{% url 'programcommittee:manage' %}">return to the management page</a>.</p>
        </div>
    </section>
{% endblock %}